version: '3.9'
services:
  mysql-keycloak:
    image: mysql:8.0.39
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-keycloak-data:/var/lib/mysql
    networks:
      - dev-net

  keycloak:
    image: keycloak/keycloak:24.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root
      KC_DB_URL_HOST: mysql-keycloak
      KC_DB_URL_DATABASE: keycloak
    command: 
      - start-dev
    volumes: 
      - ../user-storage-mysql/target/user-storage-mysql-all.jar:/opt/keycloak/providers/user-storage-mysql.jar
    depends_on:
      - mysql-keycloak
    ports:
      - "8080:8080"
    networks:
      - dev-net

  vault:
    image: hashicorp/vault:1.19
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    networks:
      - dev-net

networks:
  dev-net:
    external: true

volumes:
  mysql-keycloak-data:
